version: "3.9"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: rehab
      POSTGRES_PASSWORD: rehab
      POSTGRES_DB: rehablab
    ports: ["5432:5432"]
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports: ["5050:80"]
    depends_on: [postgres]

  # mongo (opcional)
  # mongo:
  #   image: mongo:6
  #   ports: ["27017:27017"]
  #   volumes:
  #     - mongodata:/data/db

volumes:
  pgdata:
  mongodata:
